changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Highlights
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
    - title: Build and maintenance
      labels:
        - dependencies
        - build
        - ci
    - title: Other changes
      labels:
        - "*"
